[package.extras]
typecheck = ["mypy"]

[tool.ruff]
line-length = 120
target-version = "py39"

[tool.ruff.lint]
ignore = ["A001", "A002", "A003", "A005", "ANN401", "ARG002", "ARG005", "B018", "B904", "B904", "C408", "COM812", "COM819", "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D200", "D202", "D203", "D205", "D209", "D210", "D212", "D213", "D400", "D401", "D404", "D415", "DJ007", "DTZ001", "E501", "EM101", "EM102", "F811", "FBT001", "FBT002", "FBT003", "INP001", "INT001", "ISC001", "N802", "N803", "N804", "N806", "N812", "N818", "N999", "PERF401", "PGH003", "PGH004", "PLR0913", "PLR2004", "PLR5501", "PLW0603", "PLW2901", "PT001", "PT006", "PTH118", "PTH119", "PTH120", "PTH122", "PTH123", "Q000", "RET501", "RET502", "RET503", "RET504", "RET505", "RSE102", "RUF001", "RUF002", "RUF005", "RUF009", "RUF012", "RUF015", "RUF100", "S101", "S105", "S105", "S106", "S308", "S311", "S324", "SIM102", "SIM108", "SIM300", "SLF001", "TC001", "TC002", "TC003", "TRY003", "TRY300", "UP006", "UP015", "UP017", "UP035"]
select = ["ALL"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
known-local-folder = ["apps", "core"]

[tool.ruff.lint.per-file-ignores]
"*/fixtures/*" = ["ANN"]
"*/management/*" = ["ANN"]
"*/migrations/*" = ["ANN"]
"*/tests/*" = ["ANN"]
"src/core/conf/*" = ["ANN"]

[tool.tomlsort]
all = true
in_place = true
spaces_before_inline_comment = 2
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
